name: Build Windows EXE

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --noconfirm --onefile --windowed \
            --name GproSerialMonitor \
            --add-data "GPro_Logo.jpg;." \
            serial_monitor.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GproSerialMonitor-windows
          path: dist/GproSerialMonitor.exe
          if-no-files-found: error

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build macOS app bundle
        run: |
          pyinstaller --noconfirm --windowed --name GproSerialMonitor \
            --add-data "GPro_Logo.jpg:." \
            serial_monitor.py
          # Create a zipped artifact
          pushd dist
          zip -r GproSerialMonitor-macOS.zip GproSerialMonitor.app
          popd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GproSerialMonitor-macOS
          path: dist/GproSerialMonitor-macOS.zip
          if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps for Qt
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-x11-0 libxcb-cursor0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 \
            libxcb-render-util0 libxcb-shape0 libxcb-xfixes0 libegl1 libopengl0

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Linux executable
        run: |
          pyinstaller --noconfirm --onefile --windowed \
            --name GproSerialMonitor \
            --add-data "GPro_Logo.jpg:." \
            serial_monitor.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GproSerialMonitor-linux
          path: dist/GproSerialMonitor
          if-no-files-found: error
